version: "3.9"
services:
  bazinga-db:
    image: postgres_bazinga:v1
    build: .
    container_name: "bazinga_db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bazinga
    restart: always
#    volumes:
#      - db-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - bazinga

networks:
  bazinga:
    driver: bridge
